# Generated by Django 4.2.19 on 2025-07-08 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='academic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serialnumber', models.CharField(default='', max_length=100)),
                ('course', models.CharField(default='', max_length=100)),
                ('school', models.CharField(default='', max_length=100)),
                ('start_date', models.CharField(default='', max_length=20)),
                ('end_date', models.CharField(default='', max_length=20)),
                ('standing', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='appointments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serialnumber', models.CharField(default='', max_length=100)),
                ('description', models.CharField(default='', max_length=100)),
                ('date', models.CharField(default='', max_length=100)),
                ('authority', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='cappreciation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serialnumber', models.CharField(default='', max_length=100)),
                ('award', models.CharField(default='', max_length=500)),
                ('authority', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serialnumber', models.CharField(default='', max_length=100)),
                ('student_tour', models.CharField(default='', max_length=100)),
                ('sea_duty', models.CharField(default='', max_length=100)),
                ('staff_duty', models.CharField(default='', max_length=100)),
                ('instructor_duty', models.CharField(default='', max_length=100)),
                ('command', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='cgappreciation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serialnumber', models.CharField(default='', max_length=100)),
                ('award', models.CharField(default='', max_length=500)),
                ('authority', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='cgawards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serialnumber', models.CharField(default='', max_length=100)),
                ('award', models.CharField(default='', max_length=100)),
                ('authority', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='cglcommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serialnumber', models.CharField(default='', max_length=100)),
                ('award', models.CharField(default='', max_length=500)),
                ('authority', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='cgplaque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serialnumber', models.CharField(default='', max_length=100)),
                ('award', models.CharField(default='', max_length=500)),
                ('authority', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='clcommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serialnumber', models.CharField(default='', max_length=100)),
                ('award', models.CharField(default='', max_length=500)),
                ('authority', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='coastguard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serialnumber', models.CharField(default='', max_length=100)),
                ('course', models.CharField(default='', max_length=100)),
                ('authority', models.CharField(default='', max_length=100)),
                ('school', models.CharField(default='', max_length=100)),
                ('start_date', models.CharField(default='', max_length=20)),
                ('end_date', models.CharField(default='', max_length=20)),
                ('standing', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='coastguard_foreign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serialnumber', models.CharField(default='', max_length=100)),
                ('course', models.CharField(default='', max_length=100)),
                ('authority', models.CharField(default='', max_length=100)),
                ('school', models.CharField(default='', max_length=100)),
                ('start_date', models.CharField(default='', max_length=20)),
                ('end_date', models.CharField(default='', max_length=20)),
                ('standing', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='coastguard_local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serialnumber', models.CharField(default='', max_length=100)),
                ('course', models.CharField(default='', max_length=100)),
                ('authority', models.CharField(default='', max_length=100)),
                ('school', models.CharField(default='', max_length=100)),
                ('start_date', models.CharField(default='', max_length=20)),
                ('end_date', models.CharField(default='', max_length=20)),
                ('standing', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='collateral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serialnumber', models.CharField(default='', max_length=100)),
                ('unit', models.CharField(default='', max_length=100)),
                ('duty', models.CharField(default='', max_length=100)),
                ('start_date', models.CharField(default='', max_length=20)),
                ('end_date', models.CharField(default='', max_length=20)),
                ('authority', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='collateral2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serialnumber', models.CharField(default='', max_length=100)),
                ('unit', models.CharField(default='', max_length=100)),
                ('duty', models.CharField(default='', max_length=100)),
                ('start_date', models.CharField(default='', max_length=20)),
                ('end_date', models.CharField(default='', max_length=20)),
                ('authority', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='cplaque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serialnumber', models.CharField(default='', max_length=100)),
                ('award', models.CharField(default='', max_length=500)),
                ('authority', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='dependents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serialnumber', models.CharField(default='', max_length=100)),
                ('name', models.CharField(default='', max_length=100)),
                ('relationship', models.CharField(default='', max_length=50)),
                ('birthday', models.CharField(default='', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastname', models.CharField(default='', max_length=50)),
                ('firstname', models.CharField(default='', max_length=50)),
                ('middlename', models.CharField(default='', max_length=50)),
                ('serialnumber', models.CharField(default='', max_length=50)),
                ('birthday', models.CharField(default='', max_length=15)),
                ('birthplace', models.CharField(default='', max_length=50)),
                ('nickname', models.CharField(default='', max_length=50)),
                ('gender', models.CharField(default='', max_length=10)),
                ('division', models.CharField(default='', max_length=50)),
                ('religion', models.CharField(default='', max_length=50)),
                ('height', models.CharField(default='', max_length=10)),
                ('headsize', models.CharField(default='', max_length=10)),
                ('waistsize', models.CharField(default='', max_length=10)),
                ('skincolor', models.CharField(default='', max_length=20)),
                ('distinct', models.CharField(default='', max_length=100)),
                ('civilstatus', models.CharField(default='', max_length=20)),
                ('citizenship', models.CharField(default='', max_length=20)),
                ('bloodtype', models.CharField(default='', max_length=5)),
                ('weight', models.CharField(default='', max_length=10)),
                ('footsize', models.CharField(default='', max_length=10)),
                ('bodybuild', models.CharField(default='', max_length=20)),
                ('eyecolor', models.CharField(default='', max_length=20)),
                ('haircolor', models.CharField(default='', max_length=20)),
                ('homeaddress', models.CharField(default='', max_length=100)),
                ('permanentaddress', models.CharField(default='', max_length=100)),
                ('email', models.CharField(default='', max_length=50)),
                ('contactnumber', models.CharField(default='', max_length=15)),
                ('pagibig', models.CharField(default='', max_length=20)),
                ('philhealth', models.CharField(default='', max_length=20)),
                ('sssnumber', models.CharField(default='', max_length=20)),
                ('gsis', models.CharField(default='', max_length=20)),
                ('tin', models.CharField(default='', max_length=20)),
                ('driver', models.CharField(default='', max_length=20)),
                ('rank', models.CharField(default='', max_length=100)),
                ('profile', models.FileField(default='', upload_to='profile_pics/')),
                ('status', models.CharField(default='', max_length=100)),
                ('leave_start', models.CharField(default='', max_length=20)),
                ('leave_end', models.CharField(default='', max_length=20)),
                ('status_overridden', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='eligibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serialnumber', models.CharField(default='', max_length=100)),
                ('license', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='extenduser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(default='', max_length=30)),
                ('lastname', models.CharField(default='', max_length=30)),
                ('middlename', models.CharField(default='', max_length=30)),
                ('serialnumber', models.CharField(default='', max_length=30)),
                ('birthday', models.CharField(default='', max_length=15)),
                ('division', models.CharField(default='', max_length=20)),
                ('password', models.CharField(default='', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='government',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serialnumber', models.CharField(default='', max_length=100)),
                ('position', models.CharField(default='', max_length=100)),
                ('agency', models.CharField(default='', max_length=100)),
                ('start_date', models.CharField(default='', max_length=20)),
                ('end_date', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='mappreciation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serialnumber', models.CharField(default='', max_length=100)),
                ('award', models.CharField(default='', max_length=500)),
                ('authority', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='mawards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serialnumber', models.CharField(default='', max_length=100)),
                ('award', models.CharField(default='', max_length=100)),
                ('authority', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='military',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serialnumber', models.CharField(default='', max_length=100)),
                ('course', models.CharField(default='', max_length=100)),
                ('authority', models.CharField(default='', max_length=100)),
                ('school', models.CharField(default='', max_length=100)),
                ('start_date', models.CharField(default='', max_length=20)),
                ('end_date', models.CharField(default='', max_length=20)),
                ('standing', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='military_foreign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serialnumber', models.CharField(default='', max_length=100)),
                ('course', models.CharField(default='', max_length=100)),
                ('authority', models.CharField(default='', max_length=100)),
                ('school', models.CharField(default='', max_length=100)),
                ('start_date', models.CharField(default='', max_length=20)),
                ('end_date', models.CharField(default='', max_length=20)),
                ('standing', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='military_local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serialnumber', models.CharField(default='', max_length=100)),
                ('course', models.CharField(default='', max_length=100)),
                ('authority', models.CharField(default='', max_length=100)),
                ('school', models.CharField(default='', max_length=100)),
                ('start_date', models.CharField(default='', max_length=20)),
                ('end_date', models.CharField(default='', max_length=20)),
                ('standing', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='mlcommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serialnumber', models.CharField(default='', max_length=100)),
                ('award', models.CharField(default='', max_length=500)),
                ('authority', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='mplaque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serialnumber', models.CharField(default='', max_length=100)),
                ('award', models.CharField(default='', max_length=500)),
                ('authority', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='nongovernment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serialnumber', models.CharField(default='', max_length=100)),
                ('position', models.CharField(default='', max_length=100)),
                ('agency', models.CharField(default='', max_length=100)),
                ('start_date', models.CharField(default='', max_length=20)),
                ('end_date', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serialnumber', models.CharField(default='', max_length=100)),
                ('org', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='other_trainings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serialnumber', models.CharField(default='', max_length=100)),
                ('course', models.CharField(default='', max_length=100)),
                ('school', models.CharField(default='', max_length=100)),
                ('start_date', models.CharField(default='', max_length=20)),
                ('end_date', models.CharField(default='', max_length=20)),
                ('standing', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serialnumber', models.CharField(default='', max_length=100)),
                ('profile', models.FileField(default='', upload_to='profile_pics/')),
            ],
        ),
        migrations.CreateModel(
            name='retirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serialnumber', models.CharField(default='', max_length=100)),
                ('date', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='shipboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serialnumber', models.CharField(default='', max_length=100)),
                ('unit', models.CharField(default='', max_length=100)),
                ('duty', models.CharField(default='', max_length=100)),
                ('start_date', models.CharField(default='', max_length=20)),
                ('end_date', models.CharField(default='', max_length=20)),
                ('authority', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='shorebased',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serialnumber', models.CharField(default='', max_length=100)),
                ('unit', models.CharField(default='', max_length=100)),
                ('duty', models.CharField(default='', max_length=100)),
                ('start_date', models.CharField(default='', max_length=20)),
                ('end_date', models.CharField(default='', max_length=20)),
                ('authority', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='vocational',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serialnumber', models.CharField(default='', max_length=100)),
                ('course', models.CharField(default='', max_length=100)),
                ('school', models.CharField(default='', max_length=100)),
                ('start_date', models.CharField(default='', max_length=20)),
                ('end_date', models.CharField(default='', max_length=20)),
                ('standing', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
