# Generated by Django 4.2.19 on 2025-03-06 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='extenduser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(default='', max_length=30)),
                ('lastname', models.CharField(default='', max_length=30)),
                ('middlename', models.CharField(default='', max_length=30)),
                ('serialnumber', models.CharField(default='', max_length=30)),
                ('birthday', models.CharField(default='', max_length=15)),
                ('division', models.CharField(default='', max_length=20)),
                ('password', models.CharField(default='', max_length=30)),
            ],
        ),
    ]
