# Generated by Django 4.2.19 on 2025-09-07 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cissgapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='triple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serialnumber', models.CharField(default='', max_length=100)),
                ('date', models.CharField(default='', max_length=100)),
                ('license', models.CharField(default='', max_length=100)),
                ('org', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='retirement',
            name='license',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='retirement',
            name='org',
            field=models.CharField(default='', max_length=100),
        ),
    ]
