# Generated by Django 4.2.19 on 2025-05-29 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cissgapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastname', models.CharField(default='', max_length=50)),
                ('firstname', models.CharField(default='', max_length=50)),
                ('middlename', models.CharField(default='', max_length=50)),
                ('serialnumber', models.CharField(default='', max_length=50)),
                ('birthday', models.CharField(default='', max_length=15)),
                ('birthplace', models.CharField(default='', max_length=50)),
                ('nickname', models.CharField(default='', max_length=50)),
                ('gender', models.CharField(default='', max_length=10)),
                ('religion', models.CharField(default='', max_length=50)),
                ('height', models.CharField(default='', max_length=10)),
                ('headsize', models.CharField(default='', max_length=10)),
                ('waistsize', models.CharField(default='', max_length=10)),
                ('skincolor', models.CharField(default='', max_length=20)),
                ('distinct', models.CharField(default='', max_length=100)),
                ('civilstatus', models.CharField(default='', max_length=20)),
                ('citizenship', models.CharField(default='', max_length=20)),
                ('bloodtype', models.CharField(default='', max_length=5)),
                ('weight', models.CharField(default='', max_length=10)),
                ('footsize', models.CharField(default='', max_length=10)),
                ('bodybuild', models.CharField(default='', max_length=20)),
                ('eyecolor', models.CharField(default='', max_length=20)),
                ('haircolor', models.CharField(default='', max_length=20)),
                ('homeaddress', models.CharField(default='', max_length=100)),
                ('permanentaddress', models.CharField(default='', max_length=100)),
                ('email', models.CharField(default='', max_length=50)),
                ('contactnumber', models.CharField(default='', max_length=15)),
                ('pagibig', models.CharField(default='', max_length=20)),
                ('philhealth', models.CharField(default='', max_length=20)),
                ('sssnumber', models.CharField(default='', max_length=20)),
                ('gsis', models.CharField(default='', max_length=20)),
                ('tin', models.CharField(default='', max_length=20)),
                ('driver', models.CharField(default='', max_length=20)),
                ('rank', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
