# Generated by Django 4.2.19 on 2025-03-29 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cissgapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='academic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serialnumber', models.CharField(default='', max_length=100)),
                ('course', models.CharField(default='', max_length=100)),
                ('school', models.CharField(default='', max_length=100)),
                ('start_date', models.CharField(default='', max_length=20)),
                ('end_date', models.CharField(default='', max_length=20)),
                ('standing', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
