# Generated by Django 4.2.19 on 2025-09-16 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cissgapp', '0002_triple_retirement_license_retirement_org'),
    ]

    operations = [
        migrations.CreateModel(
            name='leaves',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='details',
            name='status',
            field=models.CharField(default='Duty', max_length=100),
        ),
    ]
