# Generated by Django 4.2.19 on 2025-06-05 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cissgapp', '0002_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='dependents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serialnumber', models.CharField(default='', max_length=100)),
                ('name', models.CharField(default='', max_length=100)),
                ('relationship', models.CharField(default='', max_length=50)),
                ('birthday', models.CharField(default='', max_length=15)),
            ],
        ),
    ]
