# Generated by Django 4.2.19 on 2025-06-05 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cissgapp', '0003_dependents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='rank',
            field=models.CharField(default='', max_length=100),
        ),
    ]
