# Generated by Django 4.2.19 on 2025-09-16 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cissgapp', '0003_leaves_alter_details_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serialnumber', models.CharField(default='', max_length=100)),
                ('fullname', models.CharField(default='', max_length=100)),
                ('leave', models.CharField(default='', max_length=100)),
                ('startdate', models.CharField(default='', max_length=20)),
                ('enddate', models.CharField(default='', max_length=20)),
                ('address', models.CharField(default='', max_length=100)),
                ('order', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
