# Generated by Django 4.2.19 on 2025-06-16 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cissgapp', '0004_alter_details_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='leave',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='details',
            name='leave_end',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='details',
            name='leave_start',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='details',
            name='status',
            field=models.CharField(default='', max_length=100),
        ),
    ]
