# Generated by Django 4.2.19 on 2025-09-16 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cissgapp', '0004_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='enddate',
            field=models.DateField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='record',
            name='startdate',
            field=models.DateField(default='', max_length=20),
        ),
    ]
