# Generated by Django 4.2.19 on 2025-09-16 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cissgapp', '0005_alter_record_enddate_alter_record_startdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='status',
            field=models.CharField(default='', max_length=100),
        ),
    ]
