# Generated by Django 4.2.19 on 2025-06-17 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cissgapp', '0005_details_leave_details_leave_end_details_leave_start_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='details',
            name='leave',
        ),
    ]
