# Generated by Django 4.2.19 on 2025-06-17 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cissgapp', '0006_remove_details_leave'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='division',
            field=models.CharField(default='', max_length=50),
        ),
    ]
