# Generated by Django 4.2.19 on 2025-06-17 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cissgapp', '0007_details_division'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='status_overridden',
            field=models.BooleanField(default=False),
        ),
    ]
