# Generated by Django 4.2.19 on 2025-06-17 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cissgapp', '0008_details_status_overridden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='status_overridden',
            field=models.BooleanField(default=True),
        ),
    ]
