# Generated by Django 4.2.19 on 2025-06-18 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cissgapp', '0009_alter_details_status_overridden'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='profile',
            field=models.FileField(default='', upload_to='profile_pics/'),
        ),
    ]
